name: Trigger B on push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dispatch to 'dank-style-website'
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          # You should create a personal access token and store it in your repository
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          repo: github-actions
          owner: syedyaseenabbas
          event_type: dispatch
          message: |
            {
              "repo": "It from A" 
            }