name: Trigger actions on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Trigger another action
      run: |
        npm install @octokit/rest
        node -e "const { Octokit } = require('@octokit/rest'); const octokit = new Octokit(); octokit.repos.createDispatchEvent({ owner: '${{ github.repository_owner }}', repo: 'github-actions', event_type: 'run-action' });"
